package de.tobiasdollhofer.codecast.player.util.event.ui;

public enum UIEventType {
    PLAY_FIRST_CLICKED, PLAY_PREVIOUS_CLICKED, PLAY_PAUSE_CLICKED, PLAY_NEXT_CLICKED, PLAY_LAST_CLICKED, VOLUME_CHANGE, RESET_PLAYER, LIST_CLICKED, LIST_CLICKED_SAME,AUTOPLAY_CLICKED, JUMP_TO_CODE_CLICKED, SHOW_CODE_CLICKED, PROGRESSBAR_CLICKED
}
